/-
Copyright (c) 2025 Joël Riou. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joël Riou
-/
module

public import Mathlib.CategoryTheory.Subfunctor.Image
public import Mathlib.CategoryTheory.Yoneda

/-!
# The subpresheaf generated by a section

Given a presheaf of types `F : Cᵒᵖ ⥤ Type w` and a section `x : F.obj X`,
we define `Subfunctor.ofSection x : Subfunctor F` as the subpresheaf
of `F` generated by `x`.

-/

@[expose] public section

universe w v u

namespace CategoryTheory

variable {C : Type u} [Category.{v} C]

namespace Subfunctor

section

variable {F : Cᵒᵖ ⥤ Type w} {X : Cᵒᵖ} (x : F.obj X)

/-- The subpresheaf of `F : Cᵒᵖ ⥤ Type w` that is generated
by a section `x : F.obj X`. -/
@[simps -isSimp]
def ofSection : Subfunctor F where
  obj U := setOf (fun u ↦ ∃ (f : X ⟶ U), F.map f x = u)
  map {U V} g := by
    rintro _ ⟨f, rfl⟩
    exact ⟨f ≫ g, by simp⟩

lemma mem_ofSection_obj : x ∈ (ofSection x).obj X := ⟨𝟙 _, by simp⟩

@[simp]
lemma ofSection_le_iff (G : Subfunctor F) :
    ofSection x ≤ G ↔ x ∈ G.obj X := by
  constructor
  · intro hx
    exact hx _ (mem_ofSection_obj x)
  · rintro hx U _ ⟨f, rfl⟩
    exact G.map f hx

@[simp]
lemma ofSection_image {F' : Cᵒᵖ ⥤ Type w} (f : F ⟶ F') :
    (ofSection x).image f = ofSection (f.app _ x) := by
  aesop (add simp [image_obj, ofSection_obj, FunctorToTypes.naturality])

end

section

variable {F : Cᵒᵖ ⥤ Type v}

lemma ofSection_eq_range {X : Cᵒᵖ} (x : F.obj X) :
    ofSection x = range (yonedaEquiv.symm x) := by
  aesop (add simp [ofSection_obj, range_obj])

lemma range_eq_ofSection {X : C} (f : yoneda.obj X ⟶ F) :
    range f = ofSection (yonedaEquiv f) := by
  rw [ofSection_eq_range, Equiv.symm_apply_apply]

end

section

variable {F : Cᵒᵖ ⥤ Type max v w}

lemma ofSection_eq_range' {X : Cᵒᵖ} (x : F.obj X) :
    ofSection x = range (uliftYonedaEquiv.symm x) := by
  aesop (add simp [ofSection_obj, range_obj])

set_option backward.isDefEq.respectTransparency false in
lemma range_eq_ofSection' {X : C} (f : yoneda.obj X ⋙ uliftFunctor.{w} ⟶ F) :
    range f = ofSection (uliftYonedaEquiv f) := by
  rw [ofSection_eq_range', Equiv.symm_apply_apply]

end

@[deprecated (since := "2025-12-11")] alias Subpresheaf.ofSection := ofSection
@[deprecated (since := "2025-12-11")] alias Subpresheaf.mem_ofSection_obj := mem_ofSection_obj
@[deprecated (since := "2025-12-11")] alias Subpresheaf.ofSection_le_iff := ofSection_le_iff
@[deprecated (since := "2025-12-11")] alias Subpresheaf.ofSection_image := ofSection_image
@[deprecated (since := "2025-12-11")] alias Subpresheaf.ofSection_eq_range := ofSection_eq_range
@[deprecated (since := "2025-12-11")] alias Subpresheaf.range_eq_ofSection := range_eq_ofSection
@[deprecated (since := "2025-12-11")] alias Subpresheaf.ofSection_eq_range' := ofSection_eq_range'
@[deprecated (since := "2025-12-11")] alias Subpresheaf.range_eq_ofSection' := range_eq_ofSection'

end Subfunctor

end CategoryTheory
